recipes-core/images/intel-aero-image.bb
Add all missing dependencies to run camera-streaming-daemon on Aero
drones: avahi-client and avahi-glib.
A Daemon to handle camera streams on drones was published on https://github.com/01org/camera-streaming-daemon and it would be good to have all dependencies required to run it installed in Aero image.
=> Include dependencies necessary to run camera-streaming-daemon

recipes-support/mavlink-router/mavlink-router_0.1.bb
This atomisp module will be replaced by a proper implementation in future. For
now, just make it not trigger an ugly warning by trace infra.
=> Remove trace_printk and update mavlink-router

recipes-core/packagegroups/packagegroup-core-tools.bb
Updated tar and ps utilities to include from original sources instead of
busybox.
Issue : https://github.com/intel-aero/meta-intel-aero/issues/50
Test : Verified tar and ps utitilites in final image
Signed-off-by: Avinash Reddy Palleti <avinash.reddy.palleti@intel.com>
=> Update tools to get from original source instead of busybox

recipes-support/scripts/files/aero-reboot-update.py
Version 1.00.04 introduced /etc/os_version. Earlier releases now use
/proc/version for reporting current version.
Fix #90
=> aero-reboot-update: allow to update releases < 1.00.04

conf/bblayers.conf.sample, conf/local.conf.sample, conf/machine/intel-aero.conf, recipes-core/images/intel-aero-image.bb
This addresses issue #42. Must be used with a manifest that includes the meta-intel layer (see manifest [PR #8](https://github.com/intel-aero/intel-aero-manifest/pull/8)). Also updated machine configuration so it only has BSP related settings.
As machine configuration has changed but name remains the same it is recommended that you build in a clean environment. Alternatively cleaning up with the following commands may enable a build, but this option has not been fully tested.
`$ bitbake airmap -c cleanall` 
`$ bitbake ros-mavlink -c cleanall`
=> Updated intel-aero machine to use intel-corei7-64 from meta-intel

conf/distro/poky-aero.conf, conf/local.conf.sample
Functionality is the same as current overriden Poky design but this commit offers a place to centralize distro configuration going forward.
Variable POKY_VERSION holds the underlying Poky version (e.g. 2.1.2) and DISTRO_VERSION is set to 1.2.0 to match next planned Aero release version.
Addresses issue #97
=> Created intel-aero distro based on Poky.

recipes-core/images/intel-aero-image.bb
There was a script on eee-acpi-scripts that was handling the shutdown
button. This package got removed when we migrated to meta-intel.
Add it back.
Fix #122
=> Add back eee-acpi-scripts to handle poweroff

recipes-core/images/intel-aero-image.bb
Removing opkg and opkg-utils packages as these packages should be
dependency from tools.
Issue: https://github.com/intel-aero/meta-intel-aero/issues/117
Signed-off-by: Avinash Reddy Palleti <avinash.reddy.palleti@intel.com>
=> Remove opkg and opkg-utils packages

recipes-ros/mavros/libmavconn_0.18.7.bb, recipes-ros/mavros/mavros-extras_0.18.7.bb, recipes-ros/mavros/mavros-msgs_0.18.7.bb, recipes-ros/mavros/mavros.inc, recipes-ros/mavros/mavros_0.18.7.bb, recipes-ros/ros-mavlink/ros-mavlink_git.bbappend
Mavros version on meta-ros is too old and doesnt works with Mavlink 2.0
that is being used by the flight controller. Until they release a new
version of meta-ros with a more up to date mavros, we need to maintain
the recipes for this feature to work on Intel Aero.
Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>
---
Mavros recipes are the same as on upstream with updated version and md5 values. ros-mavlink has the same python workaround used on mavlink-router to bypass a bug on outdated meta-openembedded.
This PR also depends on PR [#5](https://github.com/intel-aero/meta-ros/pull/5) on intel-aero/meta-ros dropping the priority bumping (wont be necessary anyway).
This should address #119 and #127
=> Bump Mavros: so it properly works with Mavlink 2.0

recipes-core/images/intel-aero-image.bb
notify-led recipe will enable two services which are responsible to notify boot status
=> Add notify-led recipe

conf/layer.conf
Allow additional recipe directory in the structure.
The expected dnf recipe was not being included in the image build.
**Alternative: git mv recipes-backport/devtools/dnf -> recipes-backport/dnf**
=> layer conf: Additional dir level

recipes-support/intel-aero-repo/intel-aero-repo/intel-aero.repo
It can't have whitespaces. Renamed to Main.
=> intel-aero-repo: Change name

recipes-support/intel-aero-repo/intel-aero-repo/intel-aero.repo
Make repo disasbled by default for now.
Also avoids an issue during do_rootfs that breaks the image generation
in certain circumstances.
=> repo: Disabled by default

recipes-core/images/intel-aero-image.bb
The full wget isn't part of packagegroup-core-full-cmdline.
The stripped down version provided by busybox does not deal with https.
=> intel-aero-image: Use actual wget instead of the busybox one

recipes-core/images/intel-aero-image.bb
Enabling package management by enabling Intel Aero repo.
Issues: #224 #225
=> Enable package management by default

recipes-devtools/rpm/files/0001-Ignore-tag-number-mismatch.patch, recipes-devtools/rpm/rpm_%.bbappend
Includes changes to ignore tag number mismatch.
Changes are as per the discussion with the community.
https://github.com/rpm-software-management/rpm/issues/270#issuecomment-316893255
More details on the issue:
https://github.com/intel-aero/meta-intel-aero/issues/219
Signed-off-by: Sugnan Prabhu S <sugnan.prabhu.s@intel.com>
=> rpm: Ignore signature check failure

recipes-connectivity/networkmanager/networkmanager/firstboot-networkmanager-setup
Should be Hotspot, not Hostspot. Since we are changing it, let's make it
shorter
=> networkmanager: fix typo in connection name

recipes-support/camera-streaming-daemon/camera-streaming-daemon_0.1.bb, recipes-support/camera-streaming-daemon/files/main.conf
It is working fine when playing with QGC and gstreamer but it do not work with VLC.
=> camera-streaming-daemon: Enable down-faced camera

recipes-support/aero-http-server/aero-http-server.bb, recipes-support/aero-http-server/files/camera-def-rs-rgb.xml, recipes-support/camera-streaming-daemon/files/main.conf
For Camera control feature, an xml file with description of parameters
that the camera supports need to be hosted over http. The address of the
file will be read by the camera streaming daemon from conf file and sent to
QGC in a mavlink message. QGC will then download the xml file over http
=> [CSD] : Camera def file for Intel RS RGB camera

recipes-core/images/intel-aero-image.bb
=> intel-aero-image: Add libnss-mdns to image

recipes-core/images/intel-aero-image.bb, recipes-support/linux-firmware/linux-firmware_git.bbappend
As poky/meta completely removed reference of iwlwifi-firmware-8000C, it is
being added in bbappend as workaround. Once poky/meta fixes this issue, this
patch can be reverted.
=> Workaround for the build failure
